name: package cleanup
on:
  push:

jobs:
  try_to_list_packages:
    runs-on: ubuntu-latest
    steps:
      - name: clean packages
        uses: MobileheadHolding/github-action-purge-packages@master
        with:
          owner: github
          repo: details-dialog-element
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
